# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import hyperline_client
from hyperline_client.api.system_api import SystemApi  # noqa: E501
from hyperline_client.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = hyperline_client.api.system_api.SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gcm_signup(self):
        """Test case for gcm_signup

        For users coming from Google Marketplace to signup to Hyperline.  # noqa: E501
        """
        pass

    def test_get_all_usages(self):
        """Test case for get_all_usages

        Get Usage  # noqa: E501
        """
        pass

    def test_get_system_usage_details(self):
        """Test case for get_system_usage_details

        Get Organization Usage Details  # noqa: E501
        """
        pass

    def test_system_auth(self):
        """Test case for system_auth

        For Auth0 to verify user is authorized in backend.  # noqa: E501
        """
        pass

    def test_verify_invitation(self):
        """Test case for verify_invitation

        Verifies an invitation and onboards.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
