# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import hyperline_client
from hyperline_client.api.spark_api import SparkApi  # noqa: E501
from hyperline_client.rest import ApiException


class TestSparkApi(unittest.TestCase):
    """SparkApi unit test stubs"""

    def setUp(self):
        self.api = hyperline_client.api.spark_api.SparkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_spark_cancel_job(self):
        """Test case for spark_cancel_job

        Cancel a Spark job  # noqa: E501
        """
        pass

    def test_spark_check_job(self):
        """Test case for spark_check_job

        Check a Spark job status  # noqa: E501
        """
        pass

    def test_spark_get_job_output(self):
        """Test case for spark_get_job_output

        Get Spark job output  # noqa: E501
        """
        pass

    def test_spark_get_sql(self):
        """Test case for spark_get_sql

        Get user Spark SQL query cache  # noqa: E501
        """
        pass

    def test_spark_list_jobs(self):
        """Test case for spark_list_jobs

        List Spark jobs  # noqa: E501
        """
        pass

    def test_spark_list_saved_jobs(self):
        """Test case for spark_list_saved_jobs

        List saved spark jobs  # noqa: E501
        """
        pass

    def test_spark_save_job(self):
        """Test case for spark_save_job

        Save a spark job for pipeline  # noqa: E501
        """
        pass

    def test_spark_submit_job(self):
        """Test case for spark_submit_job

        Submit a Spark job  # noqa: E501
        """
        pass

    def test_spark_submit_sql(self):
        """Test case for spark_submit_sql

        Submit a Spark SQL job  # noqa: E501
        """
        pass

    def test_spark_update_sql(self):
        """Test case for spark_update_sql

        Update user Spark SQL query cache  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
