# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import hyperline_client
from hyperline_client.api.sql_api import SqlApi  # noqa: E501
from hyperline_client.rest import ApiException


class TestSqlApi(unittest.TestCase):
    """SqlApi unit test stubs"""

    def setUp(self):
        self.api = hyperline_client.api.sql_api.SqlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_sql_job(self):
        """Test case for check_sql_job

        Check the status of a SQL job  # noqa: E501
        """
        pass

    def test_execute_sql_query(self):
        """Test case for execute_sql_query

        Execute a SQL query  # noqa: E501
        """
        pass

    def test_get_sql_cache(self):
        """Test case for get_sql_cache

        Get user SQL query cache  # noqa: E501
        """
        pass

    def test_get_sql_job_output(self):
        """Test case for get_sql_job_output

        Get the output of a SQL job  # noqa: E501
        """
        pass

    def test_get_sql_queries(self):
        """Test case for get_sql_queries

        Get user SQL queries  # noqa: E501
        """
        pass

    def test_submit_sql_job(self):
        """Test case for submit_sql_job

        Submit a SQL job  # noqa: E501
        """
        pass

    def test_update_sql_cache(self):
        """Test case for update_sql_cache

        Update user SQL query cache  # noqa: E501
        """
        pass

    def test_update_sql_query(self):
        """Test case for update_sql_query

        Update user SQL query cache  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
