# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import hyperline_client
from hyperline_client.models.pipeline_import_error import PipelineImportError  # noqa: E501
from hyperline_client.rest import ApiException

class TestPipelineImportError(unittest.TestCase):
    """PipelineImportError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PipelineImportError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PipelineImportError`
        """
        model = hyperline_client.models.pipeline_import_error.PipelineImportError()  # noqa: E501
        if include_optional :
            return PipelineImportError(
                id = 56, 
                timestamp = '', 
                file_name = '', 
                stack_trace = ''
            )
        else :
            return PipelineImportError(
        )
        """

    def testPipelineImportError(self):
        """Test PipelineImportError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
