# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import hyperline_client
from hyperline_client.models.dated_itemized_cost import DatedItemizedCost  # noqa: E501
from hyperline_client.rest import ApiException

class TestDatedItemizedCost(unittest.TestCase):
    """DatedItemizedCost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DatedItemizedCost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatedItemizedCost`
        """
        model = hyperline_client.models.dated_itemized_cost.DatedItemizedCost()  # noqa: E501
        if include_optional :
            return DatedItemizedCost(
                cost = hyperline_client.models.itemized_cost.ItemizedCost(
                    bigquery = 56, 
                    gcs = 56, 
                    trino = 56, 
                    dataproc = 56, 
                    snowflake = 56, 
                    airflow = 56, 
                    jupyter = 56, 
                    gke = 56, ), 
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else :
            return DatedItemizedCost(
        )
        """

    def testDatedItemizedCost(self):
        """Test DatedItemizedCost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
