# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import hyperline_client
from hyperline_client.api.integration_api import IntegrationApi  # noqa: E501
from hyperline_client.rest import ApiException


class TestIntegrationApi(unittest.TestCase):
    """IntegrationApi unit test stubs"""

    def setUp(self):
        self.api = hyperline_client.api.integration_api.IntegrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_integration(self):
        """Test case for create_integration

        Create an integration  # noqa: E501
        """
        pass

    def test_delete_integration(self):
        """Test case for delete_integration

        Delete a specific integration by ID  # noqa: E501
        """
        pass

    def test_get_integration(self):
        """Test case for get_integration

        Get a specific integration by ID  # noqa: E501
        """
        pass

    def test_list_integrations(self):
        """Test case for list_integrations

        List integrations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
