# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from hyperline_client.models.saved_job import SavedJob

class SavedJobCollection(BaseModel):
    """
    SavedJobCollection
    """
    saved_jobs: Optional[conlist(SavedJob)] = None
    __properties = ["saved_jobs"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SavedJobCollection:
        """Create an instance of SavedJobCollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in saved_jobs (list)
        _items = []
        if self.saved_jobs:
            for _item in self.saved_jobs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['saved_jobs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SavedJobCollection:
        """Create an instance of SavedJobCollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SavedJobCollection.parse_obj(obj)

        _obj = SavedJobCollection.parse_obj({
            "saved_jobs": [SavedJob.from_dict(_item) for _item in obj.get("saved_jobs")] if obj.get("saved_jobs") is not None else None
        })
        return _obj


