# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class SqlQuery(BaseModel):
    """
    A Sql Query object.
    """
    next_execution_token: Optional[StrictStr] = Field(None, description="Continue execution of a query. When present, other fields are ignored.")
    name: Optional[StrictStr] = None
    types: Optional[conlist(StrictStr)] = None
    statement: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    __properties = ["next_execution_token", "name", "types", "statement", "id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SqlQuery:
        """Create an instance of SqlQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SqlQuery:
        """Create an instance of SqlQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SqlQuery.parse_obj(obj)

        _obj = SqlQuery.parse_obj({
            "next_execution_token": obj.get("next_execution_token"),
            "name": obj.get("name"),
            "types": obj.get("types"),
            "statement": obj.get("statement"),
            "id": obj.get("id")
        })
        return _obj


