# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import hyperline_client
from hyperline_client.models.stage_instance_collection import StageInstanceCollection  # noqa: E501
from hyperline_client.rest import ApiException

class TestStageInstanceCollection(unittest.TestCase):
    """StageInstanceCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StageInstanceCollection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StageInstanceCollection`
        """
        model = hyperline_client.models.stage_instance_collection.StageInstanceCollection()  # noqa: E501
        if include_optional :
            return StageInstanceCollection(
                stage_instances = [
                    hyperline_client.models.stage_instance.StageInstance(
                        pipeline_name = '', 
                        run_id = '', 
                        stage_name = '', 
                        execution_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        duration = 1.337, 
                        state = '', 
                        try_number = 56, )
                    ]
            )
        else :
            return StageInstanceCollection(
        )
        """

    def testStageInstanceCollection(self):
        """Test StageInstanceCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
