# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import hyperline_client
from hyperline_client.models.pipeline import Pipeline  # noqa: E501
from hyperline_client.rest import ApiException

class TestPipeline(unittest.TestCase):
    """Pipeline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Pipeline
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Pipeline`
        """
        model = hyperline_client.models.pipeline.Pipeline()  # noqa: E501
        if include_optional :
            return Pipeline(
                pipeline_name = '', 
                schedule = '', 
                stages = [
                    hyperline_client.models.stage.Stage(
                        stage_name = '', 
                        job_type = '', 
                        job_name = '', 
                        arguments = '', 
                        package = '', )
                    ], 
                max_active_runs = 56, 
                retries = 56, 
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                catchup = True, 
                write_test_mode = True, 
                sample_reads = True
            )
        else :
            return Pipeline(
                pipeline_name = '',
                stages = [
                    hyperline_client.models.stage.Stage(
                        stage_name = '', 
                        job_type = '', 
                        job_name = '', 
                        arguments = '', 
                        package = '', )
                    ],
        )
        """

    def testPipeline(self):
        """Test Pipeline"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
