# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import hyperline_client
from hyperline_client.models.sql_execute_response import SqlExecuteResponse  # noqa: E501
from hyperline_client.rest import ApiException

class TestSqlExecuteResponse(unittest.TestCase):
    """SqlExecuteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SqlExecuteResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SqlExecuteResponse`
        """
        model = hyperline_client.models.sql_execute_response.SqlExecuteResponse()  # noqa: E501
        if include_optional :
            return SqlExecuteResponse(
                job_id = '', 
                job_type = '', 
                query = '', 
                var_schema = [
                    hyperline_client.models.sql_field_schema.SqlFieldSchema(
                        name = '', 
                        type = '', 
                        precision = 56, 
                        scale = 56, )
                    ], 
                rows = [
                    null
                    ], 
                statistics = hyperline_client.models.sql_job_statistics.SqlJobStatistics(
                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duration = 56, 
                    total_bytes_processed = 56, )
            )
        else :
            return SqlExecuteResponse(
        )
        """

    def testSqlExecuteResponse(self):
        """Test SqlExecuteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
