# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE! 

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import hyperline_client
from hyperline_client.models.stage_instance import StageInstance  # noqa: E501
from hyperline_client.rest import ApiException

class TestStageInstance(unittest.TestCase):
    """StageInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StageInstance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StageInstance`
        """
        model = hyperline_client.models.stage_instance.StageInstance()  # noqa: E501
        if include_optional :
            return StageInstance(
                pipeline_name = '', 
                run_id = '', 
                stage_name = '', 
                execution_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                duration = 1.337, 
                state = '', 
                try_number = 56
            )
        else :
            return StageInstance(
                pipeline_name = '',
                run_id = '',
                stage_name = '',
                duration = 1.337,
                state = '',
                try_number = 56,
        )
        """

    def testStageInstance(self):
        """Test StageInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
