# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE!   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by: https://openapi-generator.tech
"""

import unittest

import hyperline_client
from hyperline_client.model.stage_instance_collection import StageInstanceCollection
from hyperline_client import configuration


class TestStageInstanceCollection(unittest.TestCase):
    """StageInstanceCollection unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
