# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE!   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by: https://openapi-generator.tech
"""

import unittest

import hyperline_hyperline_client.client
from hyperline_hyperline_client.client.model.sql_field_schema import SqlFieldSchema
from hyperline_hyperline_client.client import configuration


class TestSqlFieldSchema(unittest.TestCase):
    """SqlFieldSchema unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
