# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE!   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperline_client import schemas  # noqa: F401


class PipelineRun(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    A run of a pipeline.
    """


    class MetaOapg:
        required = {
            "run_id",
            "pipeline_name",
        }
        
        class properties:
            pipeline_name = schemas.StrSchema
            run_id = schemas.StrSchema
            state = schemas.StrSchema
            logical_date = schemas.DateTimeSchema
            config = schemas.DictSchema
            __annotations__ = {
                "pipeline_name": pipeline_name,
                "run_id": run_id,
                "state": state,
                "logical_date": logical_date,
                "config": config,
            }
    
    run_id: MetaOapg.properties.run_id
    pipeline_name: MetaOapg.properties.pipeline_name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pipeline_name"]) -> MetaOapg.properties.pipeline_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["run_id"]) -> MetaOapg.properties.run_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["state"]) -> MetaOapg.properties.state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["logical_date"]) -> MetaOapg.properties.logical_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["config"]) -> MetaOapg.properties.config: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["pipeline_name", "run_id", "state", "logical_date", "config", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pipeline_name"]) -> MetaOapg.properties.pipeline_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["run_id"]) -> MetaOapg.properties.run_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["state"]) -> typing.Union[MetaOapg.properties.state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["logical_date"]) -> typing.Union[MetaOapg.properties.logical_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["config"]) -> typing.Union[MetaOapg.properties.config, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["pipeline_name", "run_id", "state", "logical_date", "config", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        run_id: typing.Union[MetaOapg.properties.run_id, str, ],
        pipeline_name: typing.Union[MetaOapg.properties.pipeline_name, str, ],
        state: typing.Union[MetaOapg.properties.state, str, schemas.Unset] = schemas.unset,
        logical_date: typing.Union[MetaOapg.properties.logical_date, str, datetime, schemas.Unset] = schemas.unset,
        config: typing.Union[MetaOapg.properties.config, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PipelineRun':
        return super().__new__(
            cls,
            *_args,
            run_id=run_id,
            pipeline_name=pipeline_name,
            state=state,
            logical_date=logical_date,
            config=config,
            _configuration=_configuration,
            **kwargs,
        )
