# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE!   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by: https://openapi-generator.tech
"""

from hyperline_client.paths.files.post import CreateFile
from hyperline_client.paths.files_content.get import GetFileContent
from hyperline_client.paths.files_metadata.get import GetFileMetadata
from hyperline_client.paths.files_preview.get import GetFilePreview
from hyperline_client.paths.files_samples.get import GetSamples
from hyperline_client.paths.files.get import ListFiles


class FileApi(
    CreateFile,
    GetFileContent,
    GetFileMetadata,
    GetFilePreview,
    GetSamples,
    ListFiles,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
