# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE!   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by: https://openapi-generator.tech
"""

from hyperline_client.paths.spark_job_id_cancel.post import SparkCancelJob
from hyperline_client.paths.spark_job_id.get import SparkCheckJob
from hyperline_client.paths.spark_job_id_output.get import SparkGetJobOutput
from hyperline_client.paths.sparksql_edit.get import SparkGetSql
from hyperline_client.paths.spark.get import SparkListJobs
from hyperline_client.paths.spark_jobs_saved.get import SparkListSavedJobs
from hyperline_client.paths.spark_job_id_save.post import SparkSaveJob
from hyperline_client.paths.spark.post import SparkSubmitJob
from hyperline_client.paths.sparksql.post import SparkSubmitSql
from hyperline_client.paths.sparksql_edit.post import SparkUpdateSql


class SparkApi(
    SparkCancelJob,
    SparkCheckJob,
    SparkGetJobOutput,
    SparkGetSql,
    SparkListJobs,
    SparkListSavedJobs,
    SparkSaveJob,
    SparkSubmitJob,
    SparkSubmitSql,
    SparkUpdateSql,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
