# coding: utf-8

"""
    Hyperline API

    DO NOT EDIT THIS FILE!   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dev@asynclabs.xyz
    Generated by: https://openapi-generator.tech
"""

from hyperline_client.paths.sql_jobs_job_id_status.get import CheckSqlJob
from hyperline_client.paths.sql.post import ExecuteSqlQuery
from hyperline_client.paths.sql_edit.get import GetSqlCache
from hyperline_client.paths.sql_jobs_job_id_output.get import GetSqlJobOutput
from hyperline_client.paths.sql_queries.get import GetSqlQueries
from hyperline_client.paths.sql_jobs.post import SubmitSqlJob
from hyperline_client.paths.sql_edit.post import UpdateSqlCache
from hyperline_client.paths.sql_queries.post import UpdateSqlQuery


class SqlApi(
    CheckSqlJob,
    ExecuteSqlQuery,
    GetSqlCache,
    GetSqlJobOutput,
    GetSqlQueries,
    SubmitSqlJob,
    UpdateSqlCache,
    UpdateSqlQuery,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
